name: Build docker image

on:
  push:
    tags:
      - '**'
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: olegtarasov/get-tag@v2
          id: tagName
        - name: test
          run: |
             echo ${{ steps.tagName.outputs.tag }}
