name: Build docker image

on:
  push:
    branches: [ master ]
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        # - uses: mr-smithers-excellent/docker-build-push@v3
        - uses: docker/build-push-action@v1
          with:
            repository: threefoldtech/js-ng
            push: false
            tags: test
        - run: | 
            sudo apt-get update
            sudo apt-get install curl -y 
            docker save threefoldtech/js-ng:test -o js-ng-test.tar
            # curl -X POST  -H 'Authorization: bearer kiUTd9jRjgt7QB6lRh2bcpNiC2UqvTLI' https://playground.hub.grid.tf/api/flist/me/upload -F 'file=@js-ng-test.tar'
        # - name: upload to flist
        #   run: |
        #     apt-get install curl
        #     docker save threefoldtech/js-ng:test -o js-ng-test.tar
        #     curl -X POST  -H 'Authorization: bearer kiUTd9jRjgt7QB6lRh2bcpNiC2UqvTLI' https://playground.hub.grid.tf/api/flist/me/upload -F 'file=@js-ng-test.tar'
