name: Build docker image

on:
  push:
    tags:
      - "*"  
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: |
        echo ${{ github.ref }}
